title: Period
tagline: "Time range API for PHP"
description: "Period provides an immutable value object to ease working with Time Ranges"
google_analytics_tracking_id: UA-46050814-11
repository: 'period'
releases:
  current:
    version: '5.0'
    requires: 'PHP >= 8.1'
    latest: '5.3.2'
    supported_until: 'TBD'
    documentation_link: '/5.0/'
  previous:
    version: '4.0'
    requires: 'PHP >= 7.1.3'
    latest: '4.12.0 - 2022-02-21'
    supported_until: '2022-08-21'
    documentation_link: '/4.0/'
  legacy:
    version: '3.0'
    requires: 'PHP >= 5.5.9'
    latest: '3.3.0 - 2016-09-19'
    supported_until: '2017-03-18'
    documentation_link: '/3.0/'
author:
    name: 'Ignace Nyamagana Butera'
    twitter_account: 'nyamsprod'
    github_account: 'nyamsprod'
highlights:
    description: "<code>Period</code> is PHP's Time Range class. Based on ideas from <a href=\"http://verraes.net/2014/08/resolving-feature-envy-in-the-domain/\">Resolving Feature Envy in the Domain</a> by Mathias Verraes, this package extends the concept to cover all basic operations regarding time ranges."
    features:
        - Uses Immutable Value Objects
        - Uses named constructors to ease object creation
        - Covers all basic manipulations related to time range
        - Enables working with simple or complex time ranges logic
composer: '$ composer require league/period'
support: 'Once a new **major** version is released, the previous stable release remains supported for **six more months** through patches and security fixes.'
